# Generated by Django 3.1.7 on 2021-03-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebsuta_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebrisRollUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_id', models.CharField(max_length=50)),
                ('num_debris', models.IntegerField(default=0)),
            ],
        ),
    ]
